[package]
name = "halley-ui"
version = "0.1.0"
edition = "2024"
description = "Shared widgets, Taffy layout, text, and rendering for the Halley ecosystem"
license = "GPL-3.0-only"
repository = "https://github.com/saltnpepper97/halley-ui"
readme = "README.md"
keywords = ["ui", "layout", "taffy", "wayland", "accessibility"]
categories = ["gui", "graphics"]
include = ["src/**", "examples/**", "tests/**", "docs/components/**", "docs/README.md", "docs/input.md", "docs/rendering.md", "docs/accessibility.md", "/README.md", "/LICENSE", "/CHANGELOG.md", "/Cargo.toml", "/Cargo.lock"]

[features]
default = []
accessibility = ["dep:accesskit"]
accessibility-unix = ["accessibility", "dep:accesskit_unix"]

[dependencies]
cosmic-text = { version = "0.19", features = ["swash"] }
taffy = { version = "0.14", default-features = false, features = ["std", "taffy_tree", "flexbox"] }
unicode-segmentation = "1.13.3"
thiserror = "2.0.21"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
resvg = { version = "0.48.1", default-features = false }

accesskit = { version = "0.25.1", optional = true }
accesskit_unix = { version = "0.24.0", optional = true }

[package.metadata.docs.rs]
features = ["accessibility-unix"]

[dev-dependencies]
accesskit_consumer = "0.39.1"
zbus = { version = "5.19", default-features = false, features = ["async-io", "blocking-api"] }
